<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover">

 <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
    <texture filename =""/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

    <link name="base_footprint"/>
    
    <xacro:property name="constant" value="${1.0/12.0}"/>
    <xacro:property name="mass"     value="1.0"/>
    <xacro:property name="width"    value="0.8"/>
    <xacro:property name="width_sq"   value="${width*width}"/>
    <xacro:property name="height"   value="0.1"/>
    <xacro:property name="height_sq"   value="${height*height}"/>
    <xacro:property name="depth"    value="0.7"/>
    <xacro:property name="depth_sq"   value="${depth*depth}"/>
    <!-- Body-->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.8 0.7 0.1"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${width} ${depth} ${height}"/>
            </geometry>
        </collision>
        <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="1.0"/>
                <inertia ixx="${constant*mass*(height_sq + depth_sq) }" ixy="0.0" ixz="0.0"
                                   iyy="${constant*mass*(width*width + height*height)}" iyz="0.0"
                                             izz="${constant*mass*(width*width + depth*depth)}"/>
            </inertial>
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin rpy="0 0 0" xyz="0.0 0.0 0.135" />
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <xacro:macro name="wheel" params="name x y side">
        <link name="${name}_link">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.5"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
            <visual name="">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://mobile_robot/meshes/${side}_tire.stl" scale="0.005 0.005 0.005"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://mobile_robot/meshes/${side}_tire.stl" scale="0.005 0.005 0.005"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${name}_link"/>
            <!-- <origin rpy="1.57 0 0" xyz="${x} ${y} 0.0"/> -->
            <origin rpy="0 0 0" xyz="${x} ${y} 0.0"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>
    </xacro:macro>
    
    <!-- Front Right Wheel -->
    <xacro:wheel name="wheel_front_right" x="-0.25" y="0.4" side="right"/>
    <!-- Rear Left Wheel -->
    <xacro:wheel name="wheel_rear_left" x="0.25" y="-0.4" side="left"/>
    <!-- Rear Right Wheel -->
    <xacro:wheel name="wheel_rear_right" x="0.25" y="0.4" side="right"/>
    <!-- Front Left Wheel -->
    <xacro:wheel name="wheel_front_left" x="-0.25" y="-0.4" side="left"/>
    

</robot>